FROM istvan/jdk64:8u31
MAINTAINER Istvan Szukacs <leccine@gmail.com>
RUN curl -vjkL http://www.eng.lsu.edu/mirrors/apache/kafka/0.8.2.1/kafka_2.10-0.8.2.1.tgz > kafka_2.10-0.8.2.1.tgz
RUN tar xzvf kafka_2.10-0.8.2.1.tgz 
RUN rm -f kafka_2.10-0.8.2.1.tgz
RUN mv -f kafka_2.10-0.8.2.1 kafka
EXPOSE 9092
ADD server.properties kafka/config/server.properties
RUN cat kafka/config/server.properties
CMD ["bash", "kafka/bin/kafka-server-start.sh", "kafka/config/server.properties"]
